# Generated by Django 5.2.8 on 2026-07-01 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_foto_referencia_google'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='enviada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='seguido_hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='social.hashtag'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='seguido_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='places.place'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='seguido_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('seguido_usuario__isnull', False), ('seguido_local__isnull', True), ('seguido_hashtag__isnull', True)), models.Q(('seguido_usuario__isnull', True), ('seguido_local__isnull', False), ('seguido_hashtag__isnull', True)), models.Q(('seguido_usuario__isnull', True), ('seguido_local__isnull', True), ('seguido_hashtag__isnull', False)), _connector='OR'), name='alvo_unico_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('seguido_usuario__isnull', False)), fields=('seguidor', 'seguido_usuario'), name='seguidor_usuario_unico'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('seguido_local__isnull', False)), fields=('seguidor', 'seguido_local'), name='seguidor_local_unico'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('seguido_hashtag__isnull', False)), fields=('seguidor', 'seguido_hashtag'), name='seguidor_hashtag_unico'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('seguidor', models.F('seguido_usuario')), _negated=True), name='nao_pode_seguir_a_si_mesmo'),
        ),
    ]
