# Generated by Django 5.2.8 on 2026-07-04 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_foto_referencia_google'),
        ('social', '0002_comment_criado_em_follow_criado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='alvo_unico_follow',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='seguidor_hashtag_unico',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='seguido_hashtag',
        ),
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='mensagens/audios/'),
        ),
        migrations.AddField(
            model_name='message',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='mensagens/imagens/'),
        ),
        migrations.AddField(
            model_name='message',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio')], default='texto', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('seguido_usuario__isnull', False), ('seguido_local__isnull', True)), models.Q(('seguido_usuario__isnull', True), ('seguido_local__isnull', False)), _connector='OR'), name='alvo_unico_follow'),
        ),
    ]
