# Generated by Django 5.2.8 on 2026-07-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_itinerario_hashtags'),
        ('social', '0004_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_compartilhado', to='itineraries.itinerario'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('itinerario', 'Itinerário')], default='texto', max_length=10),
        ),
    ]
