# Generated by Django 5.2.8 on 2026-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_comment_parent_comment_responder_para_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duracao_segundos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='mensagens/videos/'),
        ),
        migrations.AddField(
            model_name='message',
            name='video_status',
            field=models.CharField(blank=True, choices=[('processando', 'Processando'), ('pronto', 'Pronto'), ('erro', 'Erro')], max_length=12),
        ),
        migrations.AddField(
            model_name='message',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='mensagens/videos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('itinerario', 'Itinerário')], default='texto', max_length=10),
        ),
    ]
