# Generated by Django 5.2.8 on 2026-07-30 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_message_duracao_segundos_message_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('follow', 'Novo seguidor'), ('solicitacao_seguir', 'Solicitação de follow'), ('comentario', 'Comentário no seu post'), ('resposta_comentario', 'Resposta ao seu comentário'), ('mensagem', 'Nova mensagem'), ('curtida', 'Curtida'), ('novo_post', 'Novo post de quem você segue')], max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoSeguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_seguir_recebidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_seguir_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('solicitante', 'alvo'), name='solicitacao_seguir_unica'), models.CheckConstraint(condition=models.Q(('solicitante', models.F('alvo')), _negated=True), name='nao_pode_solicitar_seguir_a_si_mesmo')],
            },
        ),
    ]
