# Generated by Django 5.2.8 on 2026-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_notification_tipo_solicitacaoseguir'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lida',
            field=models.BooleanField(default=False, help_text='Marcada True quando o destinatário abre a conversa (ver MensagensConversaView.get).'),
        ),
    ]
