# Generated by Django 5.2.8 on 2026-08-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_videopontoitinerario'),
        ('social', '0009_message_lida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('conteudo_impropio', 'Conteúdo impróprio'), ('imagem_nao_condiz', 'Imagem não condiz com o lugar'), ('informacao_falsa', 'Informação falsa'), ('imagem_ia', 'Imagem gerada por IA'), ('spam', 'Spam ou propaganda'), ('discurso_odio', 'Discurso de ódio ou discriminação'), ('outro', 'Outro')], max_length=32)),
                ('detalhe', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='itineraries.itinerario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('itinerario', 'usuario'), name='denuncia_unica_por_usuario_e_itinerario')],
            },
        ),
    ]
