# Generated by Django 5.2.8 on 2026-09-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='apagada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='respondida_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='social.message'),
        ),
    ]
