# Generated by Django 5.2.8 on 2026-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exibir_badges',
            field=models.BooleanField(default=True, help_text='Se desativado, oculta a badge de destaque no feed, posts e comentários (públicos).'),
        ),
    ]
