# Generated by Django 5.2.8 on 2026-07-11 17:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_exibir_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_exibicao',
            field=models.CharField(default='', help_text='Nome de exibição (pode ter espaços, acentos e maiúsculas).', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este nome de usuário já está em uso.'}, help_text='Identificador público (@usuario): 3 a 20 caracteres, letras minúsculas, números, "." ou "_".', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use de 3 a 20 caracteres: comece com uma letra minúscula e use apenas letras minúsculas, números, "." ou "_".', regex='^[a-z][a-z0-9_.]{2,19}$')]),
        ),
    ]
