# Generated by Django 5.2.8 on 2026-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_data_nascimento_user_genero_user_nome_exibicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_exibicao_alterado_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última troca de nome de exibição (controla o cooldown de 15 dias).', null=True),
        ),
    ]
