# Generated by Django 5.2.8 on 2026-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_nome_exibicao_alterado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conta_privada',
            field=models.BooleanField(default=False, help_text='Se ativado, itinerários e conteúdo completo do perfil só ficam visíveis para quem segue; novos seguidores exigem aprovação manual.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_comentou',
            field=models.BooleanField(default=True, help_text='Notificar quando comentarem no seu post.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_mensagem',
            field=models.BooleanField(default=True, help_text='Notificar quando alguém enviar mensagem.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_novo_post',
            field=models.BooleanField(default=True, help_text='Notificar quando alguém que você segue publicar um novo itinerário.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_respondeu',
            field=models.BooleanField(default=True, help_text='Notificar quando responderem seu comentário.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_seguiu',
            field=models.BooleanField(default=True, help_text='Notificar quando alguém seguir você.'),
        ),
        migrations.AddField(
            model_name='user',
            name='ocultar_lugares_seguidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ocultar_seguidores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ocultar_seguindo',
            field=models.BooleanField(default=False),
        ),
    ]
