# Generated by Django 5.2.8 on 2026-08-19 13:48

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_conta_privada_user_notif_comentou_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='conta_desativada_ate',
            field=models.DateTimeField(blank=True, help_text='Null = desativação indefinida (só reativa fazendo login de novo). Preenchida = reativa sozinha nesta data, mesmo sem login.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='conta_desativada_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o usuário desativa a própria conta.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='conta_excluida_em',
            field=models.DateTimeField(blank=True, help_text='Soft-delete: marca a conta como excluída (irreversível pro usuário). Os dados de verdade só são expurgados depois do período de carência — ver apps.users.tasks.expurgar_conta_excluida.', null=True),
        ),
    ]
