# Generated by Django 5.2.8 on 2026-06-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('movimentacao', models.CharField(blank=True, choices=[('vazio', 'Vazio'), ('populado', 'Populado'), ('cheio', 'Cheio')], max_length=20)),
                ('seguranca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preco_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distancia_ate_proximo', models.FloatField(blank=True, null=True)),
                ('meio_deslocamento', models.CharField(blank=True, max_length=20)),
                ('horario_estimado', models.TimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='itineraries.itinerario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_itinerario', to='places.place')),
            ],
        ),
    ]
