# Generated by Django 5.2.8 on 2026-06-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_pontoitinerario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoitinerario',
            options={'ordering': ['itinerario', 'ordem']},
        ),
    ]
