# Generated by Django 5.2.8 on 2026-06-20 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_alter_pontoitinerario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='data_fim',
            field=models.DateField(blank=True, help_text="Preenchido apenas se tipo='multi_day'", null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data em que o itinerário foi de fato realizado (não a data de publicação)', null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='publicado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='tipo',
            field=models.CharField(choices=[('day_trip', 'Day Trip'), ('multi_day', 'Multi-Day Trip')], default='day_trip', max_length=10),
        ),
    ]
