# Generated by Django 5.2.8 on 2026-06-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_itinerario_data_fim_itinerario_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
