# Generated by Django 5.2.8 on 2026-06-20 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_itinerario_status_alter_itinerario_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoitinerario',
            name='entrada_gratuita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pontoitinerario',
            name='preco_medio',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Avaliação de custo-benefício: 1 = dinheiro jogado fora, 5 = preço ótimo. Deixe em branco se entrada_gratuita=True', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
