# Generated by Django 5.2.8 on 2026-06-20 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_pontoitinerario_entrada_gratuita_and_more'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoitinerario',
            name='ordem',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pontoitinerario',
            name='preco_medio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pontoitinerario',
            name='seguranca',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='pontoitinerario',
            constraint=models.UniqueConstraint(fields=('itinerario', 'ordem'), name='ordem_unica_por_itinerario'),
        ),
    ]
