# Generated by Django 5.2.8 on 2026-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_alter_pontoitinerario_ordem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoitinerario',
            name='meio_deslocamento',
            field=models.CharField(blank=True, choices=[('a_pe', 'A pé'), ('carro', 'Carro'), ('taxi_app', 'Táxi/App de transporte'), ('transporte_publico', 'Transporte público'), ('bicicleta', 'Bicicleta')], max_length=20),
        ),
    ]
