# Generated by Django 5.2.8 on 2026-06-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_alter_pontoitinerario_meio_deslocamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPontoItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='itinerarios/fotos/')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='itineraries.pontoitinerario')),
            ],
        ),
    ]
