# Generated by Django 5.2.8 on 2026-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_itinerariobaixado_itinerariosalvo'),
        ('social', '0002_comment_criado_em_follow_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='itinerarios', to='social.hashtag'),
        ),
    ]
