# Generated by Django 5.2.8 on 2026-07-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_itinerario_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPontoItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='itinerarios/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='itinerarios/videos/thumbs/')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('pronto', 'Pronto'), ('erro', 'Erro')], default='processando', max_length=12)),
                ('erro_detalhe', models.CharField(blank=True, max_length=500)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='itineraries.pontoitinerario')),
            ],
        ),
    ]
