# Generated by Django 5.2.8 on 2026-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_videopontoitinerario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotopontoitinerario',
            name='escala',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='fotopontoitinerario',
            name='posicao_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='fotopontoitinerario',
            name='posicao_y',
            field=models.FloatField(default=50),
        ),
    ]
