# Generated by Django 5.2.8 on 2026-08-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0014_fotopontoitinerario_escala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotopontoitinerario',
            name='escala',
        ),
        migrations.RemoveField(
            model_name='fotopontoitinerario',
            name='posicao_x',
        ),
        migrations.RemoveField(
            model_name='fotopontoitinerario',
            name='posicao_y',
        ),
    ]
