# Generated by Django 5.2.8 on 2026-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='foto_referencia_google',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
