# Generated by Django 5.2.8 on 2026-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_foto_referencia_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='categoria_gamificacao',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('religioso', 'Religioso'), ('gastronomico', 'Gastronômico'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='continente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='pais_codigo',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='place',
            name='regiao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='regiao_codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
