# Generated by Django 5.2.8 on 2026-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_categoria_gamificacao_place_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='foto_referencia_google',
            field=models.TextField(blank=True, null=True),
        ),
    ]
