# Generated by Django 5.2.8 on 2026-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_foto_referencia_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='regiao_codigo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
