# Generated by Django 5.1 on 2026-06-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerariobadge',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerario'),
        ),
        migrations.AddField(
            model_name='usuariobadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badgeusuario'),
        ),
    ]
