# Generated by Django 5.2.8 on 2026-07-07 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_initial'),
        ('itineraries', '0012_itinerario_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBadgeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='badgeusuario',
            options={'ordering': ['tipo', 'criterio_valor']},
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='criterio_campo',
            field=models.CharField(choices=[('lugares_distintos_cidade', 'Lugares distintos em uma cidade'), ('cidades_distintas_regiao', 'Cidades distintas em uma região'), ('percentual_regioes_pais', '% de regiões visitadas em um país'), ('percentual_paises_continente', '% de países visitados em um continente'), ('continentes_visitados', 'Nº de continentes visitados'), ('percentual_paises_mundo', '% de países visitados no mundo'), ('km_a_pe', 'Km percorridos a pé'), ('km_carro_moto_taxi', 'Km percorridos de carro/moto/táxi/app'), ('km_transporte_publico', 'Km percorridos de transporte público'), ('km_bicicleta', 'Km percorridos de bicicleta'), ('polos_visitados', 'Polos visitados (Ártico/Antártida)'), ('lugares_culturais', 'Lugares culturais visitados'), ('lugares_religiosos', 'Lugares religiosos visitados'), ('lugares_gastronomicos', 'Lugares gastronômicos visitados')], default='lugares_distintos_cidade', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='criterio_valor',
            field=models.FloatField(default=0, help_text='Valor mínimo para conquistar este nível. Contagem absoluta ou percentual (0–100), conforme o critério.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nivel',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')], default='nivel', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariobadge',
            name='contexto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerariobadge',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='itineraries.itinerario'),
        ),
        migrations.AlterField(
            model_name='usuariobadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='gamification.badgeusuario'),
        ),
        migrations.AlterField(
            model_name='usuariobadge',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itinerariobadge',
            constraint=models.UniqueConstraint(fields=('itinerario', 'badge'), name='badge_unica_por_itinerario'),
        ),
        migrations.AddConstraint(
            model_name='usuariobadge',
            constraint=models.UniqueConstraint(fields=('usuario', 'badge', 'contexto'), name='conquista_unica_por_contexto'),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='gamification.tipobadgeusuario'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='badgeusuario',
            unique_together={('tipo', 'nivel')},
        ),
        migrations.RemoveField(
            model_name='badgeusuario',
            name='criterio',
        ),
    ]
