# Generated by Django 5.2.8 on 2026-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_tipobadgeusuario_alter_badgeusuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeitinerario',
            name='nome_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badgeusuario',
            name='nome_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='descricao_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_de',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_es',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_fr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_it',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_pt_br',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_zh_hans',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipobadgeusuario',
            name='nome_zh_hant',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
