# Generated by Django 5.2.8 on 2026-07-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0012_itinerario_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerario_ids', models.JSONField(default=list)),
                ('gerado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_cache', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_scores', models.JSONField(default=dict)),
                ('lugar_scores', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('view', 'Visualizou'), ('comment_read', 'Leu comentários'), ('save', 'Salvou'), ('use_as_base', 'Usou como base'), ('comment_post', 'Comentou')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to='itineraries.itinerario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'tipo', 'criado_em'], name='feed_feedev_usuario_572453_idx'), models.Index(fields=['itinerario', 'tipo'], name='feed_feedev_itinera_8e3f49_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similaridades_como_a', to=settings.AUTH_USER_MODEL)),
                ('usuario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similaridades_como_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario_a', 'score'], name='feed_usersi_usuario_d79a48_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario_a', 'usuario_b'), name='similaridade_unica_por_par')],
            },
        ),
    ]
