# Generated by Django 5.2.8 on 2026-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='tipo',
            field=models.CharField(choices=[('view', 'Visualizou'), ('comment_read', 'Leu comentários'), ('like', 'Curtiu'), ('save', 'Salvou'), ('use_as_base', 'Usou como base'), ('comment_post', 'Comentou')], max_length=20),
        ),
    ]
